name: lhstore
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  fl_chart: ^0.69.0
  provider: ^6.1.1
  iconsax: ^0.0.8
  get: ^4.6.6
  http: ^1.1.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  liquid_swipe: ^3.1.0
  lottie: ^3.1.3
  flutter_otp_text_field: ^1.1.1
  carousel_slider: ^5.0.0
  chewie: ^1.7.4
  video_player: ^2.8.1
  page_transition: ^2.1.0
  firebase_core: ^3.8.0
  connectivity_plus: ^6.1.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.0.5
  firebase_storage: ^12.3.6
  cached_network_image: ^3.3.0
  awesome_snackbar_content: ^0.1.1
  clipboard: ^0.1.3
  curved_navigation_bar: ^1.0.3
  flutter_launcher_icons: ^0.14.1
  rive: ^0.13.17
  flutter_iconpicker: ^4.0.1
  flutter_form_builder: ^9.5.0
  firebase_database: ^11.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/animations/success.riv
    - assets/images/slider/
    - assets/json/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/on_boarding_images/product8.png
    - assets/icons/
    - assets/logos/
    - assets/images/on_boarding_images/product2.png
    - assets/images/products/
flutter_launcher_icons:
  android: ic_launcher
  ios: true
  image_path: assets/logos/icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  flutter_lints: ^2.0.0
